apiVersion: v1
kind: Service
metadata: 
   name: cluster-svc
   namespace: default
   labels: 
     env: demo
spec: 
    type: ClusterIP 
    selector:
        app: my-app
        tier: backend
        env: demo
    ports:
      - port: 80
        targetPort: 80