apiVersion: v1
kind: Service
metadata: 
   name: nodeport-svc
   namespace: default
   labels: 
     env: demo
spec: 
    type: NodePort 
    ports:
      - port: 8080
        targetPort: 8080
        nodePort: 30001